# ╒════════════════╕
# ╞═  decorations  ╘═════════════════════════════════════════╗
# │ the look of windows, borders, transparency, etc.         ║
# ╰──────────────────────────────────────────────────────────╜

# decoration {
#     rounding = 10
# }
# general {
#     gaps_in = 10
# }
