# ╒═══════════════╕
# ╞═   keybinds   ╘═╗
# ╰─────────────────╜

# open app launcher with alt + space
unbind = $mainMod, R
bind = ALT, SPACE, exec, $menu

unbind = $mainMod, Q
unbind = $mainMod, C
bind = $mainMod, T, exec, $terminal
bind = $mainMod, Q, killactive
