# ╒════════════════╕
# ╞═     rules     ╘═════════════════════════════════════════╗
# │ window and layer rules.                                  ║
# ╰──────────────────────────────────────────────────────────╜

# window rules
windowrule {
  name = roblox-transparency
  match:class = org.vinegarhq.Sober

  opacity = 1.0 override
}

# layer rules

