# this file sources from "modules/", the base files that come with my dots, you are free to modify them but i recommend setting overrides in "custom/".

# ╒═════════════════╕
# ╞═     system     ╘═════════════════════════════════════════╗
# │ environment variables, app defaults, etc.                 ║
# ╰───────────────────────────────────────────────────────────╜

source = modules/env.conf
source = custom/env.conf
source = modules/defaults.conf
source = custom/defaults.conf

# ╒═════════════════╕
# ╞═    hardware    ╘═════════════════════════════════════════╗
# │ for the monitor config, comment the source or delete      ║
# │ if using nwg-displays. input contains sensitivity, etc.   ║
# ╰───────────────────────────────────────────────────────────╜

source = modules/monitors.conf
source = modules/input.conf

# ╒═════════════════╕
# ╞═      boot      ╘═════════════════════════════════════════╗
# │ programs that launch once on boot                         ║
# ╰───────────────────────────────────────────────────────────╜

source = modules/autostart.conf

# ╒═════════════════╕
# ╞═    aesthetic   ╘═════════════════════════════════════════╗
# │ borders, custom animations, transparency...               ║
# ╰───────────────────────────────────────────────────────────╜

source = modules/decorations.conf
source = modules/animations.conf
source = modules/layout.conf

# ╒═════════════════╕
# ╞═   interaction  ╘═════════════════════════════════════════╗
# │ keybinds and window or layer rules.                       ║
# ╰───────────────────────────────────────────────────────────╜

source = modules/keybinds.conf
source = modules/rules.conf

# ╒═════════════════╕
# ╞═     custom     ╘═════════════════════════════════════════╗
# │ optionally override modules/ with your own env vars,      ║
# │ apps, etc                                                 ║
# ╰───────────────────────────────────────────────────────────╜

source = custom/monitors.conf
source = custom/input.conf
source = custom/autostart.conf
source = custom/decorations.conf
source = custom/animations.conf
source = custom/layout.conf
source = custom/keybinds.conf
source = custom/rules.conf
