# ╒════════════════╕
# ╞═  animations   ╘═════════════════════════════════════════╗
# │ custom curves, speeds, etc.                              ║
# ╰──────────────────────────────────────────────────────────╜

# animations {
#     enabled = yes
# }
