# ╒════════════════╕
# ╞═   autostart   ╘═════════════════════════════════════════╗
# │ programs that run once on startup                        ║
# ╰──────────────────────────────────────────────────────────╜

# exec-once = waybar
# exec-once = hyprpaper
