# ╒═════════════════╕
# ╞═    defaults    ╘═════════════════════════════════════════╗
# │ default apps, modifier key, etc.                          ║
# ╰───────────────────────────────────────────────────────────╜

# $terminal = kitty
# $fileManager = dolphin
# $mainMod = SUPER
