# ╒════════════════╕
# ╞═     input     ╘═════════════════════════════════════════╗
# │ mouse and keyboard settings.                             ║
# ╰──────────────────────────────────────────────────────────╜

# input {
#     sensitivity = 0.5
#     touchpad {
#         natural_scroll = true
#     }
# }
