# ╒═══════════════╕
# ╞═    layout    ╘═════════════════════════════════════════╗
# │ dwindle, master layout settings.                        ║
# ╰─────────────────────────────────────────────────────────╜

# dwindle {
#     force_split = 2
# }
