# ╒═════════════════╕
# ╞═    monitors    ╘═════════════════════════════════════════╗
# │ delete this file or comment it out in ../hyprland.conf    ║
# │ if using nwg-displays                                     ║
# ╰───────────────────────────────────────────────────────────╜

# monitor = eDP-1, 1920x1080@60, 0x1080, 1
# monitor = HDMI-A-1, 2560x1440@144, 0x0, 1
