# ╒════════════════╕
# ╞═     rules     ╘═════════════════════════════════════════╗
# │ window and layer rules.                                  ║
# ╰──────────────────────────────────────────────────────────╜

# window rules

# windowrule {
#     # Ignore maximize requests from all apps.
#     name = suppress-maximize-events
#     match:class = .*
# 
#     suppress_event = maximize
# }

# layer rules

