# ╒═════════════════╕
# ╞═    defaults    ╘═════════════════════════════════════════╗
# │ default apps, modifier key, etc.                          ║
# ╰───────────────────────────────────────────────────────────╜

$terminal = kitty
$fileManager = dolphin
$menu = rofi -show run
$mainMod = SUPER
