# ╒═════════════════╕
# ╞═    monitors    ╘═════════════════════════════════════════╗
# │ delete this file or comment it out in ../hyprland.conf    ║
# │ if using nwg-displays                                     ║
# ╰───────────────────────────────────────────────────────────╜

monitor = , preferred, auto, 1
